### ISSUE TITLE
Crash when selecting a job

### ISSUE THREAD

**Issue by thetaprime1** [Globox1997/JobsAddon#1]
Crashes whole client when selecting any job in the jobs tab.

[latest.log](https://github.com/Globox1997/JobsAddon/files/9667579/latest.log)
[crash-2022-09-28_11.23.45-client.txt](https://github.com/Globox1997/JobsAddon/files/9667606/crash-2022-09-28_11.23.45-client.txt)

**Comment by Globox1997** [comment]
Thanks for report, was a dumb issue, fixed with [https://github.com/Globox1997/JobsAddon/commit/bbe7c67a71e5d8cc6b7f9d7cb6bdb5be7b464a00](https://github.com/Globox1997/JobsAddon/commit/bbe7c67a71e5d8cc6b7f9d7cb6bdb5be7b464a00)
