### ISSUE TITLE
Blacksmith level are easy to obtain

### ISSUE THREAD

**Issue by ghost** [Globox1997/JobsAddon#15]
### Make sure you are not opening a duplicate.

- [ ] I have searched the issue tracker and did not find an issue describing my bug.

### Description of your suggestion.

The Blacksmith level can be quickly achieved at around 30 by synthesizing dyes with flowers

**Comment by Globox1997** [comment]
Fixed with mc 1.20 version.
Turn the default smither xp in the config to 0.
