### ISSUE TITLE
Mixin crashing with new versions of TreeChop

### ISSUE THREAD

**Issue by hammertater** [Globox1997/JobsAddon#17]
### Minecraft Version

1.19.x

### Mod Loader Version

NA

### Mod Version

NA

### Describe the Issue

Crash at startup when using both JobsAddon and TreeChop 0.18.3(+). Reported to me in https://github.com/hammertater/treechop/issues/216. The root cause is a mixin for an internal TreeChop class that has changed in a recent update, same problem as described in https://github.com/Globox1997/LevelZ/issues/191. I only glanced at your code, but I think the TreeChop event AFTER_CHOP (https://github.com/hammertater/treechop/blob/main/fabric/src/main/java/ht/treechop/api/TreeChopEvents.java) should work for your compatibility. I'd be happy to help if anything isn't clear, or if the API needs to be expanded

The problem was reported for Minecraft 1.19.2, but I expect it'll also crash for 1.20.

### latest.log

See the crash log in https://github.com/hammertater/treechop/issues/216

**Comment by Globox1997** [comment]
hey hammertater,
thanks for the info.
AFTER_CHOP event does not provide which blocks got chopped right? 
cause the xp in jobsaddon is calculated by which block id got broken by the player

**Comment by Globox1997** [comment]
hit me up on discord Globox_Z

**Comment by Globox1997** [comment]
Fixed with [https://github.com/Globox1997/JobsAddon/commit/fc45161e1bef67f6f8700b727af2273f00b02bbf](https://github.com/Globox1997/JobsAddon/commit/fc45161e1bef67f6f8700b727af2273f00b02bbf)

**Comment by cwingrav** [comment]
Just to verify behavior. If someone is using an axe, but doesn't have the level to use it, it now chops the entire block but does not drop it. If someone has the levelz skill to use the axe, it functions correctly.
