### ISSUE TITLE
[bug] Infinite exp glitch

### ISSUE THREAD

**Issue by noah1510** [Globox1997/JobsAddon#18]
It is possible to get infinite smithing experience by repeatedly crafting iron ingots into iron blocks and back.

Should also work with nuggets but is not as profitable.

An option to not reward when crating the item could mitigate this.

**Comment by Globox1997** [comment]
I guess you are using the 1.19 version, turn the smither default xp to 0 in the config to fix this.

**Comment by noah1510** [comment]
I use the latest version on 1.20.1 with the default configuration.
