### ISSUE TITLE
Compatibility with "FallingTree"

### ISSUE THREAD

**Issue by Allomere** [Globox1997/JobsAddon#3]
When you cut trees with the mod "FallingTree" the LumberJack job doesnt recognise that you have cuted a tree

**Comment by Globox1997** [comment]
Added with [https://github.com/Globox1997/JobsAddon/commit/5b675a85b30bdf217f55a01837a25dbc845386ab](https://github.com/Globox1997/JobsAddon/commit/5b675a85b30bdf217f55a01837a25dbc845386ab)
