### ISSUE TITLE
 Mining Skill Not Working (mining stone)

### ISSUE THREAD

**Issue by WalterFan6969** [Globox1997/JobsAddon#4]
When you max out the mining skill, or on any other level of mining  you can never mine stone. Version is 1.19.2

**Comment by Globox1997** [comment]
Is this an addon issue or in the base mod?

**Comment by Akiway** [comment]
I also have this problem and I'm only using base mod. Mining stone with wooden pickaxe doesn't drop cobblestone. Same version.

**Comment by xR4YM0ND** [comment]
delete the config, delete datpacks, try again

**Comment by Globox1997** [comment]
In the latest version of levelz there is a gui setting which shows a block tooltip on the screen when the block is not unlocked.
if it is not unlocked, it won't drop itself cause tools and blocks have different restrictions
