### ISSUE TITLE
[Compat] JobsAddon and Harvest Scythes

### ISSUE THREAD

**Issue by CasualJeremy** [Globox1997/JobsAddon#6]
Harvest Scythes currently yields no experience with JobsAddon's Farming profession

**Comment by Globox1997** [comment]
Added with [https://github.com/Globox1997/JobsAddon/commit/405ba97854cfc2e88b35fb4a2ce5ff14f6c06192](https://github.com/Globox1997/JobsAddon/commit/405ba97854cfc2e88b35fb4a2ce5ff14f6c06192)
