### ISSUE TITLE
[Compat] JobsAddon with Farmer's Delight

### ISSUE THREAD

**Issue by CasualJeremy** [Globox1997/JobsAddon#7]
I've tried to create a datapack that supports Farmer's Delight crops for the Farming profession but nothing works. I got the wild variations of the plants (Wild Cabbage, Wild Onion... etc) to work properly but the crops themselves don't produce any experience. I've attached my configuration below for reference.

File location:
`datapack\data\jobsaddon\farmer\farmersdelight.json`

_Uploaded as a .txt because Github doesn't support .json uploads_
[farmersdelight.txt](https://github.com/Globox1997/JobsAddon/files/10262520/farmersdelight.txt)

**Comment by xR4YM0ND** [comment]
you need a new folder in `datapack/data/jobsaddon/tags/items/farmer_breaking_items.json`
In there make the json like so:

![farmer_breaking_items json](https://user-images.githubusercontent.com/97298005/208726773-883cd91c-6c59-4ad1-8a75-988dfb362ec6.png)


The farmer_job.json should look like this: ( only items & crafting )
![farmer_job json](https://user-images.githubusercontent.com/97298005/208726784-2472ad5b-2d96-4c10-b6f4-d6007884f4f0.png)

**Comment by CasualJeremy** [comment]
Perfect, thank you!
